const ec2Instance = {
     "Architecture":"x86_64",
     "BlockDeviceMappings":[
        {
           "DeviceName":"/dev/sda1",
           "Ebs":{
              "AttachTime":"2025-03-20T22:27:58.000Z",
              "DeleteOnTermination":true,
              "Status":"attached",
              "VolumeId":"vol-0d31587c5e1d7c752"
           }
        }
     ],
     "ClientToken":"978878a7-b52c-4e0f-9d52-fd49a3eb7322",
     "EbsOptimized":false,
     "EnaSupport":true,
     "Hypervisor":"xen",
     "IamInstanceProfile":{
        "Arn":"arn:aws:iam::674152176016:instance-profile/stable-diffusions-ec2",
        "Id":"AIPAZZ5UZ3GIIE6FICGV7"
     },
     "InstanceLifecycle":"spot",
     "NetworkInterfaces":[
        {
           "Association":{
              "IpOwnerId":"amazon",
              "PublicDnsName":"ec2-3-81-112-179.compute-1.amazonaws.com",
              "PublicIp":"3.81.112.179"
           },
           "Attachment":{
              "AttachTime":"2025-03-20T22:27:57.000Z",
              "AttachmentId":"eni-attach-049ab8a44b77959bc",
              "DeleteOnTermination":true,
              "DeviceIndex":0,
              "Status":"attached",
              "NetworkCardIndex":0
           },
           "Description":"",
           "Groups":[
              {
                 "GroupId":"sg-0405dc62640988b9c",
                 "GroupName":"launch-wizard-1"
              }
           ],
           "Ipv6Addresses":[
              
           ],
           "MacAddress":"0e:3f:d1:f5:2d:8d",
           "NetworkInterfaceId":"eni-02a4e4ea8477be574",
           "OwnerId":"674152176016",
           "PrivateDnsName":"ip-172-31-19-140.ec2.internal",
           "PrivateIpAddress":"172.31.19.140",
           "PrivateIpAddresses":[
              {
                 "Association":{
                    "IpOwnerId":"amazon",
                    "PublicDnsName":"ec2-3-81-112-179.compute-1.amazonaws.com",
                    "PublicIp":"3.81.112.179"
                 },
                 "Primary":true,
                 "PrivateDnsName":"ip-172-31-19-140.ec2.internal",
                 "PrivateIpAddress":"172.31.19.140"
              }
           ],
           "SourceDestCheck":true,
           "Status":"in-use",
           "SubnetId":"subnet-bb9ecde3",
           "VpcId":"vpc-ae2b80c9",
           "InterfaceType":"interface",
           "Operator":{
              "Managed":false
           }
        }
     ],
     "RootDeviceName":"/dev/sda1",
     "RootDeviceType":"ebs",
     "SecurityGroups":[
        {
           "GroupId":"sg-0405dc62640988b9c",
           "GroupName":"launch-wizard-1"
        }
     ],
     "SourceDestCheck":true,
     "SpotInstanceRequestId":"sir-r8m739pn",
     "Tags":[
        {
           "Key":"aws:ec2launchtemplate:version",
           "Value":"2"
        },
        {
           "Key":"aws:ec2launchtemplate:id",
           "Value":"lt-07b96c92864a38bdd"
        }
     ],
     "VirtualizationType":"hvm",
     "CpuOptions":{
        "CoreCount":2,
        "ThreadsPerCore":2
     },
     "CapacityReservationSpecification":{
        "CapacityReservationPreference":"open"
     },
     "HibernationOptions":{
        "Configured":false
     },
     "MetadataOptions":{
        "State":"applied",
        "HttpTokens":"optional",
        "HttpPutResponseHopLimit":1,
        "HttpEndpoint":"enabled",
        "HttpProtocolIpv6":"disabled",
        "InstanceMetadataTags":"disabled"
     },
     "EnclaveOptions":{
        "Enabled":false
     },
     "BootMode":"uefi-preferred",
     "PlatformDetails":"Linux/UNIX",
     "UsageOperation":"RunInstances",
     "UsageOperationUpdateTime":"2025-03-20T22:27:57.000Z",
     "PrivateDnsNameOptions":{
        "HostnameType":"ip-name",
        "EnableResourceNameDnsARecord":false,
        "EnableResourceNameDnsAAAARecord":false
     },
     "MaintenanceOptions":{
        "AutoRecovery":"default"
     },
     "CurrentInstanceBootMode":"uefi",
     "NetworkPerformanceOptions":{
        "BandwidthWeighting":"default"
     },
     "Operator":{
        "Managed":false
     },
     "InstanceId":"i-0052634ac62923522",
     "ImageId":"ami-059f5520f8750f598",
     "State":{
        "Code":16,
        "Name":"running"
     },
     "PrivateDnsName":"ip-172-31-19-140.ec2.internal",
     "PublicDnsName":"ec2-3-81-112-179.compute-1.amazonaws.com",
     "StateTransitionReason":"",
     "KeyName":"us-east-1-ramadoka",
     "AmiLaunchIndex":0,
     "ProductCodes":[
        
     ],
     "InstanceType":"g6.xlarge",
     "LaunchTime":"2025-03-21T13:28:22.000Z",
     "Placement":{
        "GroupName":"",
        "Tenancy":"default",
        "AvailabilityZone":"us-east-1a"
     },
     "Monitoring":{
        "State":"disabled"
     },
     "SubnetId":"subnet-bb9ecde3",
     "VpcId":"vpc-ae2b80c9",
     "PrivateIpAddress":"172.31.19.140",
     "PublicIpAddress":"3.81.112.179"
  }

export type EC2Instance = typeof ec2Instance;